models.py
import string
from .extensions import db
from random import choices

#class that forms the links between the original url and the shortened url
class URL_Connector(db.Model):

    CONST_MAX_STRING_LENGTH = 600
    CONST_MAX_SHORT_URL_LENGTH = 5

    id = db.Column(db.Integer, primary_key=True)
    original_url = db.Column(db.String(CONST_MAX_STRING_LENGTH))
    short_url = db.Column(db.String(CONST_MAX_SHORT_URL_LENGTH), unique = True)

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.short_url = self.create_shortened_url()

    def create_shortened_url(self):

        #combines all alphanumeric chars (upper and lower case (62 total)) into a list
        alphanumeric_chars = string.digits + string.ascii_letters

        #randomly creates an object  of length 'CONST_MAX_SHORT_URL_LENGTH'
        #916132832 combinations
        short_url = ''.join(choices(alphanumeric_chars, k = URL_Connector.CONST_MAX_SHORT_URL_LENGTH))

        #a check to see if shortened url already exists
        #if short url already exists in database function is called again
        link = self.query.filter_by(short_url=short_url).first() #use exists?

        if link:
            return self.create_shortened_url()

        return short_url

__init__.py
from flask import Flask
from .routes import short
from .extensions import db

def create_app(config_file='settings.py'):
    url_shortener_app = Flask(__name__)
    url_shortener_app.config.from_pyfile(config_file)

    db.init_app(url_shortener_app)
    url_shortener_app.register_blueprint(short)

    return url_shortener_app

routes.py
from flask import Blueprint, redirect, request, render_template
from .models import URL_Connector
from .extensions import db

short = Blueprint('short', __name__)

@short.route('/<short_url>')
def redirect_to_url(short_url):
    link = URL_Connector.query.filter_by(short_url=short_url).first_or_404()
    return redirect(link.original_url)

#home page
@short.route('/')
def index():
    return render_template('index.html')

#page that displays new shortened url
@short.route('/add_link', methods=['POST'])
def add_link():
    original_url = request.form['original_url']
    url_connection = URL_Connector(original_url=original_url)
    db.session.add(url_connection)
    db.session.commit()
    return render_template('shortened_url.html',
                           new_link = url_connection.short_url, original_url=url_connection.original_url)

#error handling page for non-existent urls
@short.errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404

templates/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Cormac's URL Shortener</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
    rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
    crossorigin="anonymous">
</head>

<body style="background-color:Linen;">
    <section class="section">
        <div><h1 style="text-align:center">Cormac's URL Shortener</h1></div>
        <div class="container">
            <form method="POST" action="{{ url_for('short.add_link')}}">
                <div class="mb-3">
                    <label for="Original URL" class="form-label"><b>Original URL</b></label>
                    <input type="text" class="form-control" placeholder="Enter URL here..." name="original_url"></div>
                <button type="submit" class="btn btn-primary">Shorten URL</button>
            </form>
        </div>
    </section>
</body>
</html>

templates/shortened_url.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Cormac's URL Shortener</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
    rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
    crossorigin="anonymous">
  </head>

  <body style="background-color:Linen;">
    <section class="section">
        <div class="container">
            <form>
                <div class="mb-3">
                    <label for="Original URL" class="form-label"><b>Original URL</b></label>
                    <input type="text"  class="form-control" name="original_url" value="{{ original_url}}">
                </div>
                <div class="mb-3">
                    <label for="Shortened URL" class="form-label"><b>Shortened URL</b></label>
                        <input type="text" class="form-control" name="shortened_url" value="{{ url_for('short.redirect_to_url', short_url=new_link, _external=True)}}">
                    </div>
                </div>
            </form>
        </div>
     </section>
  </body>
</html>